### ISSUE TITLE
Customization details in gulpfile.js

### ISSUE THREAD

**Issue by pgorripati1** [dentness/PHELogs#30]
Comments on the changes in gulpfile.js file can help the changes done as part of the development

https://github.com/dentness/PHELogs/blob/26d688f074cccc40ea30624ab6ba7d018147fffd/web/gulpfile.js#L1

**Comment by dentness** [comment]
Gulp is a task running used during development.  This provides a one-command tool to build/run/watch the application.  When updates are saved, Gulp attempts to rebuild and rerun the app without further interaction from the developer.

This file was copied from either the Node.JS site or the Gulp site.  Any comments I add will likely be misleading.
